# T3 Foundation Gemstone Project [t3gemstone.org]
# SPDX-License-Identifier: Apache-2.0
---
version: "3"

vars:
  NAME: "t3-gem-nextcloud"
  BUILD_PARAMS: -Zzstd -z0
  NEXTCLOUD_MD5CHKSUM: 69c1e63c3c68e220dcc1b27d5f3d051b
  NEXTCLOUD_DLINK: https://download.nextcloud.com/server/releases/nextcloud-31.0.8.tar.bz2

tasks:
  default:
    silent: true
    cmds:
      - task --list-all --summary

  download-nextcloud:
    cmds:
      - mkdir -p src/deb/tmp
      - if [ ! -f src/deb/tmp/nextcloud.tar.bz2 ] || [ "$(md5sum src/deb/tmp/nextcloud.tar.bz2 | cut -d' ' -f1)" != "{{ .NEXTCLOUD_MD5CHKSUM }}" ]; then rm -rf src/deb/tmp/nextcloud.tar*; wget {{ .NEXTCLOUD_DLINK }} -O src/deb/tmp/nextcloud.tar.bz2; fi

  prepare:
    cmds:
      - task: download-nextcloud
      - mkdir -p src/deb/etc/t3-gem-nextcloud/
      - cp src/common/* src/deb/etc/t3-gem-nextcloud/

  build:
    cmds:
      - task: prepare
      - mkdir -p build/
      - fakeroot chown -R root:root ./src/deb
      - fakeroot dpkg-deb {{ .BUILD_PARAMS }} --build ./src/deb ./build
  
  release:
    cmds:
      - task: prepare
      - mkdir -p release
      - fakeroot chown -R root:root ./src/deb
      - fakeroot dpkg-deb --build ./src/deb ./release

  docker-start:
    dir: src/docker/
    cmds:
      - docker compose up -d

  docker-stop:
    dir: src/docker/
    cmds:
      - docker compose down
      
  clean: rm -rf build release
